#index:
#    path: /
#    controller: App\Controller\DefaultController::index
Auth:
  resource: 'App\Controller\AuthController'
  type: annotation

MongoTest:
  resource: 'App\Controller\MongoTestController'
  type: annotation
Search:
  resource: 'App\Controller\SearchController'
  type: annotation
Post:
  resource: 'App\Controller\PostController'
  type: annotation

Category:
  resource: 'App\Controller\CategoryController'
  type: annotation

MicroPost:
  resource: 'App\Controller\MicroPostController'
  type: annotation