#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

gesdinet_jwt_refresh_token:
  path:     /api/token/refresh
  defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
ApiAuth:
  resource: 'App\Controller\Api\AuthController'
  type: annotation
Api:
  resource: 'App\Controller\Api\PostController'
  type: annotation
Auth:
  resource: 'App\Controller\AuthController'
  type: annotation

MongoTest:
  resource: 'App\Controller\MongoTestController'
  type: annotation
Search:
  resource: 'App\Controller\SearchController'
  type: annotation
Post:
  resource: 'App\Controller\PostController'
  type: annotation

Category:
  resource: 'App\Controller\CategoryController'
  type: annotation

MicroPost:
  resource: 'App\Controller\MicroPostController'
  type: annotation